### ISSUE TITLE
Values for the bottleneck dims and max_tokens_per_batch in paper

### ISSUE THREAD

**Issue by KMnP** [jxhe/unified-parameter-efficient-tuning#17]
Hi, thanks for the great work! Can I ask two questions regarding the implementation details in the paper?

1. what are the bottleneck dims  (`attn_bn` and `ffn_bn`) for prefix-tuning, Adapter used in Fig.4 of the main paper?
2. for en-ro (as in `exps/run_en_ro.sh`), did you use the default `max_tokens_per_batch=4096` for all bottleneck dims? If not, is it possible to share the `max_tokens_per_batch`  values you used? 

Thanks for your help in advance!

**Comment by jxhe** [comment]
Thanks for your interest! For your questions:

1. In Figure 4, prefix tuning has `attn_bn` of 1,30,200,512 and Adapter has `ffn_bn` of 1,30,200,512,1024, as descried in the experiment setup.

2. Yes we used   `max_tokens_per_batch=4096` for all bottleneck dims

**Comment by KMnP** [comment]
Thanks for the quick reply!  Sorry I missed the values form the setup section and Appendix A.1 somehow..
