### ISSUE TITLE
The implementation details of Pfreiffer Adapter for MT task

### ISSUE THREAD

**Issue by BaohaoLiao** [jxhe/unified-parameter-efficient-tuning#23]
Hi,

you implemented Pfeiffer Adapter as one of your baselines for MT. Could you point me to the related codes? 

The original Pfeiffer adapter is implemented with post-norm. But for MBART, it is trained with pre-norm. I wonder how I should use the residual connection and layernorm.

**Comment by jxhe** [comment]
Hi,

I think we just ran the pfeiffer adapter from the [adapter-transformers](https://github.com/adapter-hub/adapter-transformers) package for baseline comparison -- they should have already taken care of the pre-norm version of Pfeiffer adapter in MBART.

**Comment by BaohaoLiao** [comment]
I see. Will check their code. Thank you!
